### ISSUE TITLE
Spellcheck and names

### ISSUE THREAD

**Issue by adamlaki** [conedevelopment/bite-sized-a11y#11]
Hey Viktor @szepeviktor ,

do you have any idea how we can avoid this in the future (it tries to correct a name):

https://github.com/conedevelopment/bite-sized-a11y/actions/runs/6492045759/job/17630302030

Thank you!

**Comment by szepeviktor** [comment]
Typos is a superior spellchecker. Use that.
But proper names should be ignored: `Manuel Matuzovic`
