### ISSUE TITLE
some inaccurate info in main areas of wai-aria post

### ISSUE THREAD

**Issue by scottaohara** [conedevelopment/bite-sized-a11y#2]
hi there,  I came across this project and reviewed https://bite-sized-a11y.com/16-the-main-areas-of-wai-aria/ today, and noticed that some of the things it called out weren't entirely accurate.  I understand the purpose of these posts is to be short and to the point, and rather than getting into some of the nuances to smooth over some of these issues, I thought it might make more sense to just revise some of the examples.

For instance:
the way the 'roles' is described makes  it read like roles are used to define landmark regions. And the example given for a `role=banner` being the same as `<header>` is not always accurate, as a header can be exposed as a `role=banner` OR depending on how its used, it may be exposed no differently than a `<div>`.

Properties are not just additional extensions to existing elements, though there are some properties that do extend the features of HTML.  Rather, they represent information about an element that can be communicated via the browser's accessibility tree to assistive technologies.  The example given of using aria-labelledby to extend the label element doesn't make sense as written, as it comes across as saying that the attribute could be used with the label element (it's prohibited to use on this element).  Maybe instead suggest that aria-labelledby can be used to give an article element an accessible name?

States is actually ok, but for the fact that aria-busy has some spotty support. A more robust example - like using aria-pressed on a button to create a toggle button - would probably be a better example as (outside of unintended regressions which may happen) the attribute's support is solid.

I hope these suggestions help.  Thanks

**Comment by adamlaki** [comment]
Hey Scott,

thank you, it helps a lot! 

I will soon clarify the post with the help of your guidance.

**Comment by adamlaki** [comment]
@scottaohara do you have time for a revision? Is it any better?

https://github.com/conedevelopment/bite-sized-a11y/blob/update-%2316/src/posts/the-main-areas-of-wai-aria.md

Thank you!

**Comment by scottaohara** [comment]
i'll make a PR, since i didn't get to see what you revised until after it was merged

**Comment by adamlaki** [comment]
Thanks!

Here is the original: https://github.com/conedevelopment/bite-sized-a11y/blob/9057564d680b20922e6dfac061d76ddee6207e1e/src/posts/the-main-areas-of-wai-aria.md

And here is the updated: https://github.com/conedevelopment/bite-sized-a11y/blob/master/src/posts/the-main-areas-of-wai-aria.md
